CREATE TABLE IF NOT EXISTS board_status (
  club_id INTEGER PRIMARY KEY REFERENCES clubs(id) ON DELETE CASCADE,
  confidence INTEGER NOT NULL DEFAULT 70,
  patience INTEGER NOT NULL DEFAULT 70,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS board_goals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  club_id INTEGER NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  season TEXT NOT NULL,
  goal_type TEXT NOT NULL,
  target_value INTEGER NOT NULL DEFAULT 0,
  current_value INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(club_id, season, goal_type)
);
INSERT OR IGNORE INTO board_status(club_id) SELECT id FROM clubs;
