use serde::Serialize;
use tauri::State;
use crate::commands::AppState;

#[derive(Serialize, sqlx::FromRow)]
pub struct BoardStatusRow { pub confidence:i64, pub patience:i64 }
#[derive(Serialize, sqlx::FromRow)]
pub struct BoardGoalRow { pub id:i64, pub season:String, pub goal_type:String, pub target_value:i64, pub current_value:i64, pub status:String }
#[derive(Serialize, sqlx::FromRow)]
pub struct BoardMeetingRow { pub id:i64, pub date:String, pub topic:String, pub decision:String, pub confidence_delta:i64, pub patience_delta:i64, pub notes:String }

async fn pool(state:&State<'_,AppState>)->Result<sqlx::SqlitePool,String>{state.pool.lock().map_err(|e|e.to_string())?.clone().ok_or("No hay partida".into())}

#[tauri::command]
pub async fn get_board_status(state:State<'_,AppState>)->Result<BoardStatusRow,String>{let p=pool(&state).await?;let (club,):(i64,)=sqlx::query_as("SELECT user_club_id FROM game_state WHERE id=1").fetch_one(&p).await.map_err(|e|e.to_string())?;sqlx::query_as("SELECT confidence,patience FROM board_status WHERE club_id=?").bind(club).fetch_one(&p).await.map_err(|e|e.to_string())}
#[tauri::command]
pub async fn get_board_goals(state:State<'_,AppState>)->Result<Vec<BoardGoalRow>,String>{let p=pool(&state).await?;let (club,):(i64,)=sqlx::query_as("SELECT user_club_id FROM game_state WHERE id=1").fetch_one(&p).await.map_err(|e|e.to_string())?;let(season,):(String,)=sqlx::query_as("SELECT season FROM game_state WHERE id=1").fetch_one(&p).await.map_err(|e|e.to_string())?;sqlx::query("INSERT OR IGNORE INTO board_goals(club_id,season,goal_type,target_value) VALUES(?,?, 'league_position', 4)").bind(club).bind(&season).execute(&p).await.map_err(|e|e.to_string())?;sqlx::query_as("SELECT id,season,goal_type,target_value,current_value,status FROM board_goals WHERE club_id=? AND season=? ORDER BY id").bind(club).bind(season).fetch_all(&p).await.map_err(|e|e.to_string())}
#[tauri::command]
pub async fn get_board_meetings(state:State<'_,AppState>)->Result<Vec<BoardMeetingRow>,String>{let p=pool(&state).await?;let(club,):(i64,)=sqlx::query_as("SELECT user_club_id FROM game_state WHERE id=1").fetch_one(&p).await.map_err(|e|e.to_string())?;sqlx::query_as("SELECT id,date,topic,decision,confidence_delta,patience_delta,notes FROM board_meetings WHERE club_id=? ORDER BY date DESC,id DESC LIMIT 30").bind(club).fetch_all(&p).await.map_err(|e|e.to_string())}
#[tauri::command]
pub async fn hold_board_meeting(state:State<'_,AppState>,topic:String,decision:String)->Result<BoardStatusRow,String>{let p=pool(&state).await?;let(club,):(i64,)=sqlx::query_as("SELECT user_club_id FROM game_state WHERE id=1").fetch_one(&p).await.map_err(|e|e.to_string())?;let(date,):(String,)=sqlx::query_as("SELECT game_date FROM game_state WHERE id=1").fetch_one(&p).await.map_err(|e|e.to_string())?;let(conf,pat,notes) = match decision.as_str(){"invest"=>(3,-1,"Solicitar inversión en plantilla"),"stability"=>(1,2,"Priorizar estabilidad y objetivos"),_=> (0,0,"Mantener el plan actual")};sqlx::query("INSERT INTO board_meetings(club_id,date,topic,decision,confidence_delta,patience_delta,notes) VALUES(?,?,?,?,?,?,?)").bind(club).bind(&date).bind(topic).bind(decision).bind(conf).bind(pat).bind(notes).execute(&p).await.map_err(|e|e.to_string())?;sqlx::query("UPDATE board_status SET confidence=MIN(100,MAX(0,confidence+?)),patience=MIN(100,MAX(0,patience+?)),updated_at=CURRENT_TIMESTAMP WHERE club_id=?").bind(conf).bind(pat).bind(club).execute(&p).await.map_err(|e|e.to_string())?;sqlx::query_as("SELECT confidence,patience FROM board_status WHERE club_id=?").bind(club).fetch_one(&p).await.map_err(|e|e.to_string())}

pub async fn evaluate_board(pool:&sqlx::SqlitePool)->Result<(),String>{let club:Option<(i64,)>=sqlx::query_as("SELECT user_club_id FROM game_state WHERE id=1").fetch_optional(pool).await.map_err(|e|e.to_string())?;let Some((club,))=club else{return Ok(())};let(season,):(String,)=sqlx::query_as("SELECT season FROM game_state WHERE id=1").fetch_one(pool).await.map_err(|e|e.to_string())?;let(pos,):(Option<i64>,)=sqlx::query_as("SELECT position FROM league_standings WHERE club_id=? AND season=? ORDER BY position LIMIT 1").bind(club).bind(&season).fetch_optional(pool).await.map_err(|e|e.to_string())?.unwrap_or((None,));if let Some(position)=pos{sqlx::query("UPDATE board_goals SET current_value=?,status=CASE WHEN ?<=target_value THEN 'met' ELSE 'active' END WHERE club_id=? AND season=? AND goal_type='league_position'").bind(position).bind(position).bind(club).bind(&season).execute(pool).await.map_err(|e|e.to_string())?;let delta=if position<=4{1}else{-1};sqlx::query("UPDATE board_status SET confidence=MIN(100,MAX(0,confidence+?)),updated_at=CURRENT_TIMESTAMP WHERE club_id=?").bind(delta).bind(club).execute(pool).await.map_err(|e|e.to_string())?;}Ok(())}
