use serde::Serialize;
use tauri::State;
use crate::commands::AppState;

#[derive(Serialize, sqlx::FromRow)]
pub struct NationalPlayerRow { pub player_id:i64, pub player_name:String, pub nation_id:i64, pub nation_name:String, pub flag_path:Option<String>, pub club_name:Option<String>, pub position:String, pub selected:i64, pub callup_status:String }
#[derive(Serialize, sqlx::FromRow)]
pub struct NationalManagerRow { pub nation_id:i64, pub staff_id:i64, pub staff_name:String, pub role:String, pub tactical:i64, pub motivating:i64 }
#[derive(Serialize, sqlx::FromRow)]
pub struct InternationalFixtureRow { pub id:i64, pub date:String, pub home_nation_id:i64, pub home_nation:String, pub home_flag_path:Option<String>, pub away_nation_id:i64, pub away_nation:String, pub away_flag_path:Option<String>, pub status:String, pub home_score:i64, pub away_score:i64 }

async fn get_pool(state: &State<'_, AppState>) -> Result<sqlx::SqlitePool, String> { state.pool.lock().map_err(|e|e.to_string())?.clone().ok_or("No hay partida".into()) }

#[tauri::command]
pub async fn get_national_players(state: State<'_, AppState>, nation_id:i64) -> Result<Vec<NationalPlayerRow>, String> { let pool=get_pool(&state).await?; sqlx::query_as::<_,NationalPlayerRow>("SELECT p.id,p.common_name,?,n.name,n.flag_path,c.name,COALESCE(pp.pos,'UNI'),COALESCE(ns.selected,0),COALESCE(ns.callup_status,'eligible') FROM players p JOIN nations n ON n.id=? LEFT JOIN contracts ct ON ct.player_id=p.id AND ct.is_active=1 LEFT JOIN clubs c ON c.id=ct.club_id LEFT JOIN national_team_squads ns ON ns.player_id=p.id AND ns.nation_id=? LEFT JOIN (SELECT player_id,CASE WHEN por_natural>=18 THEN 'POR' WHEN cie_natural>=18 THEN 'CIE' WHEN piv_natural>=18 THEN 'PIV' WHEN ala_natural>=18 THEN 'ALA' ELSE 'UNI' END pos FROM player_positions) pp ON pp.player_id=p.id WHERE p.is_retired=0 AND (p.nation_id=? OR p.second_nation_id=?) ORDER BY selected DESC,p.common_name").bind(nation_id).bind(nation_id).bind(nation_id).bind(nation_id).bind(nation_id).fetch_all(&pool).await.map_err(|e|e.to_string()) }

#[tauri::command]
pub async fn set_national_callup(state: State<'_, AppState>, nation_id:i64, player_id:i64, selected:bool) -> Result<(), String> { let pool=get_pool(&state).await?; let eligible:(i64,)=sqlx::query_as("SELECT COUNT(*) FROM players WHERE id=? AND (nation_id=? OR second_nation_id=?) AND is_retired=0").bind(player_id).bind(nation_id).bind(nation_id).fetch_one(&pool).await.map_err(|e|e.to_string())?; if eligible.0==0{return Err("Jugador no elegible para esta selección".into())} let (selected_count,):(i64,)=sqlx::query_as("SELECT COUNT(*) FROM national_team_squads WHERE nation_id=? AND selected=1 AND player_id<>?").bind(nation_id).bind(player_id).fetch_one(&pool).await.map_err(|e|e.to_string())?; if selected&&selected_count>=14{return Err("Una convocatoria no puede superar los 14 jugadores".into())} sqlx::query("INSERT INTO national_team_squads(nation_id,player_id,selected,callup_status) VALUES(?,?,?,?) ON CONFLICT(nation_id,player_id) DO UPDATE SET selected=excluded.selected,callup_status=excluded.callup_status").bind(nation_id).bind(player_id).bind(selected as i64).bind(if selected{"called_up"}else{"eligible"}).execute(&pool).await.map_err(|e|e.to_string())?; Ok(()) }

#[tauri::command]
pub async fn get_free_national_staff(state: State<'_, AppState>, nation_id:i64)->Result<Vec<(i64,String,String,i64,i64)>,String>{let pool=get_pool(&state).await?;crate::commands::free_staff_for_nation(&pool,nation_id).await}
#[tauri::command]
pub async fn get_national_manager(state: State<'_, AppState>, nation_id:i64)->Result<Option<NationalManagerRow>,String>{let pool=get_pool(&state).await?;sqlx::query_as::<_,NationalManagerRow>("SELECT nts.nation_id,s.id,s.common_name,nts.role,COALESCE(s.tactical,0),COALESCE(s.motivating,0) FROM national_team_staff nts JOIN staff s ON s.id=nts.staff_id WHERE nts.nation_id=? AND nts.active=1").bind(nation_id).fetch_optional(&pool).await.map_err(|e|e.to_string())}
#[tauri::command]
pub async fn assign_national_manager(state: State<'_, AppState>, nation_id:i64, staff_id:i64)->Result<(),String>{let pool=get_pool(&state).await?;let valid:(i64,)=sqlx::query_as("SELECT COUNT(*) FROM staff WHERE id=? AND (club_id IS NULL OR club_id=0)").bind(staff_id).fetch_one(&pool).await.map_err(|e|e.to_string())?;if valid.0==0{return Err("El seleccionador debe estar libre".into())}sqlx::query("INSERT INTO national_team_staff(nation_id,staff_id,role,active) VALUES(?,?, 'manager',1) ON CONFLICT(nation_id,role) DO UPDATE SET staff_id=excluded.staff_id,active=1").bind(nation_id).bind(staff_id).execute(&pool).await.map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]
pub async fn get_international_fixtures(state: State<'_, AppState>, nation_id:i64)->Result<Vec<InternationalFixtureRow>,String>{let pool=get_pool(&state).await?;sqlx::query_as::<_,InternationalFixtureRow>("SELECT im.id,im.date,im.home_nation_id,hn.name,hn.flag_path,im.away_nation_id,an.name,an.flag_path,im.status,im.home_score,im.away_score FROM international_matches im JOIN nations hn ON hn.id=im.home_nation_id JOIN nations an ON an.id=im.away_nation_id WHERE im.home_nation_id=? OR im.away_nation_id=? ORDER BY im.date").bind(nation_id).bind(nation_id).fetch_all(&pool).await.map_err(|e|e.to_string())}

pub async fn generate_international_windows(pool:&sqlx::SqlitePool)->Result<(),String>{let(season,):(String,)=sqlx::query_as("SELECT season FROM game_state WHERE id=1").fetch_one(pool).await.map_err(|e|e.to_string())?;let year:i32=season.split('/').next().and_then(|v|v.parse().ok()).unwrap_or(2026);for(start,end,kind)in[(format!("{}-09-07",year),format!("{}-09-15",year),"friendly"),(format!("{}-10-05",year),format!("{}-10-13",year),"qualifier"),(format!("{}-11-09",year),format!("{}-11-17",year),"friendly"),(format!("{}-03-22",year+1),format!("{}-03-30",year+1),"qualifier")]{sqlx::query("INSERT OR IGNORE INTO international_windows(season,start_date,end_date,window_type) VALUES(?,?,?,?)").bind(&season).bind(start).bind(end).bind(kind).execute(pool).await.map_err(|e|e.to_string())?;}let(count,):(i64,)=sqlx::query_as("SELECT COUNT(*) FROM international_matches WHERE season=?").bind(&season).fetch_one(pool).await.map_err(|e|e.to_string())?;if count==0{let nations:Vec<(i64,)>=sqlx::query_as("SELECT id FROM nations WHERE futsal_level>=60 ORDER BY futsal_level DESC,id LIMIT 16").fetch_all(pool).await.map_err(|e|e.to_string())?;let date=format!("{}-09-10",year);let comp:Option<(i64,)>=sqlx::query_as("SELECT id FROM competitions WHERE kind='national_team' ORDER BY id LIMIT 1").fetch_optional(pool).await.map_err(|e|e.to_string())?;for pair in nations.chunks(2){if pair.len()==2{let(mid,):(i64,)=sqlx::query_as("INSERT INTO international_matches(competition_id,season,date,home_nation_id,away_nation_id,status) VALUES(?,?,?,?,?,'scheduled') RETURNING id").bind(comp.map(|v|v.0)).bind(&season).bind(&date).bind(pair[0].0).bind(pair[1].0).fetch_one(pool).await.map_err(|e|e.to_string())?;let(wid,):(i64,)=sqlx::query_as("SELECT id FROM international_windows WHERE season=? AND start_date<=? AND end_date>=? LIMIT 1").bind(&season).bind(&date).bind(&date).fetch_one(pool).await.map_err(|e|e.to_string())?;sqlx::query("INSERT INTO national_fixtures(international_match_id,window_id) VALUES(?,?)").bind(mid).bind(wid).execute(pool).await.map_err(|e|e.to_string())?;}}}Ok(())}

#[cfg(test)]
mod tests {
 use super::*;
 use crate::{db,world};
 #[tokio::test]
 async fn international_windows_are_idempotent(){let pool=db::init_memory_pool().await.unwrap();world::seed_world(&pool).await.unwrap();generate_international_windows(&pool).await.unwrap();generate_international_windows(&pool).await.unwrap();let(w,):(i64,)=sqlx::query_as("SELECT COUNT(*) FROM international_windows").fetch_one(&pool).await.unwrap();let(m,):(i64,)=sqlx::query_as("SELECT COUNT(*) FROM international_matches").fetch_one(&pool).await.unwrap();assert_eq!(w,4);assert_eq!(m,8);}
 #[tokio::test]
 async fn callup_limit_and_dual_nationality(){let pool=db::init_memory_pool().await.unwrap();world::seed_world(&pool).await.unwrap();let(a, b):(i64,i64)=sqlx::query_as("SELECT id, second_nation_id FROM players WHERE second_nation_id IS NOT NULL LIMIT 1").fetch_one(&pool).await.unwrap();let nation:(i64,)=sqlx::query_as("SELECT second_nation_id FROM players WHERE id=?").bind(a).fetch_one(&pool).await.unwrap();let result=sqlx::query("INSERT INTO national_team_squads(nation_id,player_id,selected,callup_status) VALUES(?,?,1,'called_up')").bind(nation.0).bind(a).execute(&pool).await;assert!(result.is_ok());for i in 0..13{let(pid,):(i64,)=sqlx::query_as("SELECT id FROM players WHERE id<>? LIMIT 1 OFFSET ?").bind(a).bind(i).fetch_one(&pool).await.unwrap();let _=sqlx::query("INSERT OR IGNORE INTO national_team_squads(nation_id,player_id,selected,callup_status) VALUES(?,?,1,'called_up')").bind(nation.0).bind(pid).execute(&pool).await;}let(count,):(i64,)=sqlx::query_as("SELECT COUNT(*) FROM national_team_squads WHERE nation_id=? AND selected=1").bind(nation.0).fetch_one(&pool).await.unwrap();assert!(count>=1);let _=b;}
}
