import { useEffect, useState } from "react";
import { api, type BoardGoalRow, type BoardStatusRow, type BoardMeetingRow } from "../../api";
import { Panel } from "../ui";

export default function BoardView(){
 const [status,setStatus]=useState<BoardStatusRow|null>(null); const [goals,setGoals]=useState<BoardGoalRow[]>([]); const [meetings,setMeetings]=useState<BoardMeetingRow[]>([]); const [decision,setDecision]=useState("stability"); const [error,setError]=useState<string|null>(null);
 const load=()=>Promise.all([api.getBoardStatus(),api.getBoardGoals(),api.getBoardMeetings()]).then(([s,g,m])=>{setStatus(s);setGoals(g);setMeetings(m)}).catch(e=>setError(String(e))); useEffect(()=>{load()},[]);
 return <div className="mx-auto max-w-5xl space-y-4 p-4 lg:p-6"><div><div className="text-xs uppercase tracking-widest text-fm-accent">Gestión del club</div><h2 className="text-2xl font-black">Directiva</h2><p className="text-sm text-fm-dim">Consulta la confianza de la directiva y los objetivos de la temporada.</p></div>{error&&<div role="alert" className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}<div className="grid gap-3 sm:grid-cols-2">{[["Confianza",status?.confidence], ["Paciencia",status?.patience]].map(([label,value])=><Panel key={String(label)} className="p-4"><div className="text-xs uppercase tracking-widest text-fm-dim">{label}</div><div className="mt-2 text-3xl font-black text-fm-accent">{value ?? "—"}<span className="ml-1 text-sm text-fm-dim">/100</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-fm-bg"><div className="h-full rounded-full bg-fm-accent" style={{width:`${Number(value??0)}%`}}/></div></Panel>)}</div><Panel className="p-4"><div className="text-xs uppercase tracking-widest text-fm-dim">Objetivos</div><div className="mt-3 space-y-2">{goals.map(g=><div key={g.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-fm-bg px-3 py-2 text-sm"><span className="font-semibold">{g.goal_type === "league_position" ? "Terminar entre los cuatro primeros" : g.goal_type}</span><span className={g.status === "met" ? "text-emerald-300" : "text-fm-dim"}>{g.status === "met" ? "Cumplido" : `Posición actual: ${g.current_value || "—"}`}</span></div>)}{!goals.length&&<div className="text-fm-dim">No hay objetivos registrados.</div>}</div></Panel><Panel className="p-4"><div className="text-xs uppercase tracking-widest text-fm-dim">Reunión con la directiva</div><div className="mt-3 flex flex-wrap gap-2"><select value={decision} onChange={e=>setDecision(e.target.value)} className="rounded-lg border border-fm-border bg-fm-bg px-3 py-2 text-sm"><option value="stability">Priorizar estabilidad</option><option value="invest">Solicitar inversión</option><option value="neutral">Mantener el plan</option></select><button onClick={async()=>{try{await api.holdBoardMeeting("Plan de temporada",decision);load()}catch(e){setError(String(e))}}} className="rounded-lg bg-fm-accent px-3 py-2 text-sm font-bold text-black">Celebrar reunión</button></div><div className="mt-3 space-y-2">{meetings.slice(0,5).map(m=><div key={m.id} className="rounded bg-fm-bg px-3 py-2 text-xs"><strong>{m.date}</strong> · {m.notes} <span className="ml-2 text-fm-dim">Confianza {m.confidence_delta>=0?"+":""}{m.confidence_delta}</span></div>)}</div></Panel></div>;
}
