import { useEffect, useState } from "react";
import { api, type BoardGoalRow, type BoardStatusRow } from "../../api";
import { Panel } from "../ui";

export default function BoardView(){
 const [status,setStatus]=useState<BoardStatusRow|null>(null); const [goals,setGoals]=useState<BoardGoalRow[]>([]); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{Promise.all([api.getBoardStatus(),api.getBoardGoals()]).then(([s,g])=>{setStatus(s);setGoals(g)}).catch(e=>setError(String(e)))},[]);
 return <div className="mx-auto max-w-5xl space-y-4 p-4 lg:p-6"><div><div className="text-xs uppercase tracking-widest text-fm-accent">Gestión del club</div><h2 className="text-2xl font-black">Directiva</h2><p className="text-sm text-fm-dim">Consulta la confianza de la directiva y los objetivos de la temporada.</p></div>{error&&<div role="alert" className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}<div className="grid gap-3 sm:grid-cols-2">{[["Confianza",status?.confidence], ["Paciencia",status?.patience]].map(([label,value])=><Panel key={String(label)} className="p-4"><div className="text-xs uppercase tracking-widest text-fm-dim">{label}</div><div className="mt-2 text-3xl font-black text-fm-accent">{value ?? "—"}<span className="ml-1 text-sm text-fm-dim">/100</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-fm-bg"><div className="h-full rounded-full bg-fm-accent" style={{width:`${Number(value??0)}%`}}/></div></Panel>)}</div><Panel className="p-4"><div className="text-xs uppercase tracking-widest text-fm-dim">Objetivos</div><div className="mt-3 space-y-2">{goals.map(g=><div key={g.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-fm-bg px-3 py-2 text-sm"><span className="font-semibold">{g.goal_type === "league_position" ? "Terminar entre los cuatro primeros" : g.goal_type}</span><span className={g.status === "met" ? "text-emerald-300" : "text-fm-dim"}>{g.status === "met" ? "Cumplido" : `Posición actual: ${g.current_value || "—"}`}</span></div>)}{!goals.length&&<div className="text-fm-dim">No hay objetivos registrados.</div>}</div></Panel></div>;
}
