import { useEffect, useState } from "react";
import { api, type LoanRow, type MarketPlayer, type OfferRow, type PlayerRow } from "../../api";
import { EmptyState, MetricCard, Panel, StatusBadge } from "../ui";
import Flag from "../Flag";

export default function MarketView() {
  const [market, setMarket] = useState<MarketPlayer[]>([]), [offers, setOffers] = useState<OfferRow[]>([]), [freeAgents, setFreeAgents] = useState<MarketPlayer[]>([]), [loans, setLoans] = useState<LoanRow[]>([]), [squad, setSquad] = useState<PlayerRow[]>([]);
  const [loading, setLoading] = useState(true), [fees, setFees] = useState<Record<number, string>>({}), [msg, setMsg] = useState<string | null>(null);
  const [loanPlayer, setLoanPlayer] = useState<number | null>(null), [loanClub, setLoanClub] = useState(""), [loanMonths, setLoanMonths] = useState(6);
  const load = async () => { setLoading(true); try { const [m,o,f,l,state] = await Promise.all([api.getMarket(),api.getOffers(),api.getFreeAgents(),api.getLoans(),api.getGameState()]); setMarket(m);setOffers(o);setFreeAgents(f);setLoans(l);setSquad(state.user_club_id?await api.getSquad(state.user_club_id):[]); } catch(e){setMsg(String(e));} finally{setLoading(false);} };
  useEffect(()=>{load();},[]);
  const offer = async (p:MarketPlayer) => { const fee=Number(fees[p.id]||p.value); if(!fee||fee<=0){setMsg("Introduce una oferta válida");return;} try{setMsg(await api.makeOffer(p.id,fee));await load();}catch(e){setMsg(String(e));} };
  const sign = async (p:MarketPlayer) => { try{setMsg(await api.signFreeAgent(p.id,Math.max(500,Math.round(p.ca*18)),3));await load();}catch(e){setMsg(String(e));} };
  const offerLoan = async () => { if(!loanPlayer||!loanClub){setMsg("Selecciona jugador y club destino");return;} try{setMsg(await api.offerLoan(loanPlayer,Number(loanClub),loanMonths,0));setLoanPlayer(null);await load();}catch(e){setMsg(String(e));} };
  const respond = async (id:number,accept:boolean) => { try{setMsg(await api.respondOffer(id,accept));await load();}catch(e){setMsg(String(e));} };
  if(loading)return <div className="mx-auto max-w-6xl p-6"><Panel className="p-8 text-center text-fm-dim">Cargando mercado…</Panel></div>;
  return <div className="mx-auto max-w-6xl space-y-5 p-4 lg:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[0.2em] text-fm-accent">Operaciones</div><h2 className="text-xl font-black">Mercado de fichajes</h2></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><MetricCard label="Disponibles" value={market.length} detail="En mercado" tone="text-fm-sky-300"/><MetricCard label="Agentes libres" value={freeAgents.length} detail="Sin contrato" tone="text-emerald-300"/><MetricCard label="Cesiones" value={loans.length} detail="Activas" tone="text-fm-amber-300"/></div><button onClick={load} className="rounded-lg border border-fm-border bg-fm-panel px-3 py-1.5 text-sm">Actualizar</button></div>
    {msg&&<div className="rounded-lg border border-fm-accent/30 bg-fm-accent/10 px-3 py-2 text-sm">{msg}</div>}
    <Panel className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 text-xs font-bold uppercase tracking-widest text-fm-dim">Agentes libres · {freeAgents.length}</div>{freeAgents.length? <div className="divide-y divide-fm-border">{freeAgents.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 px-3 py-2 text-sm"><span><b>{p.name}</b> · {p.position} · CA {p.ca}</span><button onClick={()=>sign(p)} className="rounded bg-fm-accent px-3 py-1 text-xs font-bold text-black">Fichar</button></div>)}</div>:<EmptyState title="Sin agentes libres" description="No hay jugadores disponibles sin contrato."/>}</Panel>
    <Panel className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 text-xs font-bold uppercase tracking-widest text-fm-dim">Jugadores disponibles · {market.length}</div>{market.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-fm-bg text-xs uppercase tracking-widest text-fm-dim"><tr><th className="px-3 py-2 text-left">Jugador</th><th>Edad</th><th>Pos</th><th>CA</th><th>Club</th><th>Valor</th><th>Oferta</th><th/></tr></thead><tbody>{market.map(p=><tr key={p.id} className="border-t border-fm-border hover:bg-fm-panel2"><td className="px-3 py-2"><div className="font-semibold"><Flag src={p.flag_path} alt={p.nation} className="mr-2 inline h-3 w-5" />{p.name}</div><div className="text-xs text-fm-dim">{p.nation} · {p.secondary_position?`${p.position}/${p.secondary_position}`:p.position}</div></td><td className="text-center">{p.age}</td><td className="text-center"><StatusBadge>{p.position}</StatusBadge></td><td className="text-center font-mono">{p.ca===0?"? / ?":`${p.ca}/${p.pa}`}<div className="text-[10px] text-fm-dim">Info {p.knowledge}%</div></td><td className="text-xs">{p.club_short}</td><td className="text-right font-mono text-xs">{p.value?`€${Math.round(p.value).toLocaleString()}`:"Desconocido"}</td><td><input value={fees[p.id]??String(Math.round(p.value))} onChange={e=>setFees({...fees,[p.id]:e.target.value})} className="w-24 rounded border border-fm-border bg-fm-bg px-2 py-1 font-mono text-xs"/></td><td><button onClick={()=>offer(p)} disabled={!p.value} className="rounded bg-fm-accent px-3 py-1 text-xs font-bold text-black disabled:opacity-40">Ofertar</button></td></tr>)}</tbody></table></div>:<EmptyState title="Mercado vacío" description="No hay jugadores visibles con el nivel de conocimiento actual."/>}</Panel>
    <Panel className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 text-xs font-bold uppercase tracking-widest text-fm-dim">Ofrecer jugadores en cesión</div><div className="flex flex-wrap gap-2 p-3"><select value={loanPlayer??""} onChange={e=>setLoanPlayer(Number(e.target.value)||null)} className="rounded border border-fm-border bg-fm-bg px-2 py-1 text-sm"><option value="">Jugador propio…</option>{squad.map(p=><option key={p.id} value={p.id}>{p.common_name} · {p.position}</option>)}</select><input value={loanClub} onChange={e=>setLoanClub(e.target.value)} placeholder="ID club destino" type="number" className="w-32 rounded border border-fm-border bg-fm-bg px-2 py-1 text-sm"/><select value={loanMonths} onChange={e=>setLoanMonths(Number(e.target.value))} className="rounded border border-fm-border bg-fm-bg px-2 py-1 text-sm"><option value={3}>3 meses</option><option value={6}>6 meses</option><option value={12}>12 meses</option></select><button onClick={offerLoan} className="rounded bg-fm-accent px-3 py-1 text-sm font-bold text-black">Ofrecer</button></div></Panel>
    <Panel className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 text-xs font-bold uppercase tracking-widest text-fm-dim">Cesiones activas · {loans.length}</div>{loans.length?<div className="divide-y divide-fm-border">{loans.map(l=><div key={l.player_id} className="px-3 py-2 text-sm"><b>{l.player_name}</b> · {l.from_club} → {l.to_club} · hasta {l.loan_until}</div>)}</div>:<EmptyState title="Sin cesiones activas"/>}</Panel>
    <Panel className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 text-xs font-bold uppercase tracking-widest text-fm-dim">Ofertas · {offers.length}</div>{offers.length?<div className="divide-y divide-fm-border">{offers.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-2 px-3 py-2 text-sm"><span><b>{o.player_name}</b> · {o.from_club} → {o.to_club} · €{Math.round(o.fee).toLocaleString()} · <StatusBadge tone={o.status==="pending"?"warning":o.status==="accepted"?"success":"danger"}>{o.status}</StatusBadge></span>{o.status==="pending"&&<span className="flex gap-1"><button onClick={()=>respond(o.id,true)} className="rounded bg-emerald-600 px-2 py-1 text-xs font-bold">Aceptar</button><button onClick={()=>respond(o.id,false)} className="rounded bg-rose-600 px-2 py-1 text-xs font-bold">Rechazar</button></span>}</div>)}</div>:<EmptyState title="Sin ofertas" description="Las nuevas ofertas aparecerán aquí."/>}</Panel>
  </div>;
}
