import { useEffect, useMemo, useState } from "react";
import { api, type ScoutingReport, type ScoutingState } from "../../api";
import { EmptyState, MetricCard, Panel, StatusBadge } from "../ui";

export default function ScoutingView() {
  const [data,setData]=useState<ScoutingState|null>(null); const [nation,setNation]=useState(0); const [filter,setFilter]=useState(""); const [sort,setSort]=useState<"knowledge"|"ca"|"pa">("knowledge"); const [msg,setMsg]=useState<string|null>(null); const [report,setReport]=useState<ScoutingReport|null>(null);
  const load=()=>api.getScouting().then(d=>{setData(d);if(!nation&&d.nations[0])setNation(d.nations[0][0]);}).catch(e=>setMsg(String(e))); useEffect(()=>{load();},[]);
  const assign=async()=>{try{setMsg(await api.scoutNation(nation));load();}catch(e){setMsg(String(e));}};
  const openReport=async(id:number)=>{try{setReport(await api.getScoutingReport(id));}catch(e){setMsg(String(e));}};
  const players=useMemo(()=>data?.players.filter(p=>`${p.name} ${p.club_name} ${p.nation} ${p.position}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>sort==="knowledge"?b.knowledge-a.knowledge:sort==="ca"?b.ca_max-a.ca_max:b.pa_max-a.pa_max)??[],[data,filter,sort]);
  if(!data)return <div className="mx-auto max-w-6xl p-6"><Panel className="p-8 text-center text-fm-dim">Cargando ojeo… {msg}</Panel></div>;
  return <div className="mx-auto max-w-6xl space-y-5 p-4 lg:p-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[0.2em] text-fm-accent">Inteligencia deportiva</div><h2 className="text-xl font-black">Centro de ojeo</h2><p className="text-sm text-fm-dim">Descubre talento antes de comprometer tu presupuesto.</p></div><div className="grid grid-cols-2 gap-2"><MetricCard label="Conocimiento" value={`${data.knowledge_level}%`} detail="Red de ojeo"/><MetricCard label="Scouts" value={`${data.active_assignments}/${data.max_scouts}`} detail="Asignaciones" tone="text-fm-sky-300"/></div></div>
    {msg&&<div className="rounded-lg border border-fm-accent/30 bg-fm-accent/10 px-3 py-2 text-sm">{msg}</div>}
    <Panel className="p-3"><div className="flex flex-wrap gap-2"><select value={nation} onChange={e=>setNation(Number(e.target.value))} className="rounded-lg border border-fm-border bg-fm-bg px-3 py-2 text-sm">{data.nations.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button onClick={assign} className="rounded-lg bg-fm-accent px-4 py-2 text-sm font-bold text-black">Asignar scout</button><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar jugador, club o posición…" className="min-w-56 flex-1 rounded-lg border border-fm-border bg-fm-bg px-3 py-2 text-sm"/><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)} className="rounded-lg border border-fm-border bg-fm-bg px-3 py-2 text-sm"><option value="knowledge">Ordenar: conocimiento</option><option value="ca">Ordenar: CA estimada</option><option value="pa">Ordenar: PA estimada</option></select></div></Panel>
    <Panel className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 text-xs font-bold uppercase tracking-widest text-fm-dim">Jugadores conocidos · {players.length}</div>{players.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-fm-bg text-xs text-fm-dim"><tr><th className="px-3 py-2 text-left">Jugador</th><th>Club</th><th>Pos</th><th>Info</th><th>CA</th><th>PA</th><th>Informe</th></tr></thead><tbody>{players.map(p=><tr key={p.player_id} className="border-t border-fm-border hover:bg-fm-panel2"><td className="px-3 py-2 font-semibold">{p.flag_path?<img src={p.flag_path} alt={p.nation} className="mr-2 inline h-3 w-5 rounded object-cover"/>:"🏳️"}{p.name}<div className="text-xs text-fm-dim">{p.nation} · {p.secondary_position?`${p.position}/${p.secondary_position}`:p.position}</div></td><td className="text-xs">{p.club_name}</td><td className="text-center"><StatusBadge>{p.position}</StatusBadge></td><td className="text-center font-mono text-fm-accent">{p.knowledge}%</td><td className="text-center font-mono">{p.ca_min}-{p.ca_max}</td><td className="text-center font-mono">{p.pa_min}-{p.pa_max}</td><td className="text-center"><button onClick={()=>openReport(p.player_id)} className="text-xs text-fm-accent underline">Ver informe</button></td></tr>)}</tbody></table></div>:<EmptyState title="Sin jugadores descubiertos" description="Asigna un scout para empezar a descubrir perfiles."/>}</Panel>
    {report&&<Panel className="border-fm-accent/30 p-4"><div className="flex items-center justify-between"><h3 className="font-black">Informe · {report.player.name}</h3><button onClick={()=>setReport(null)} className="text-fm-dim">Cerrar</button></div><div className="mt-2 grid gap-3 sm:grid-cols-2"><div><div className="text-xs uppercase tracking-widest text-emerald-400">Fortalezas</div><div>{report.strengths.join(" · ")}</div></div><div><div className="text-xs uppercase tracking-widest text-rose-400">Debilidades</div><div>{report.weaknesses.join(" · ")}</div></div></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{report.attributes.map(a=><div key={a.name} className="rounded bg-fm-bg p-2 text-xs"><div className="text-fm-dim">{a.name}</div><b>{a.value_min}-{a.value_max}</b></div>)}</div></Panel>}
  </div>;
}
