import { useEffect, useState } from "react";
import { api, type PlayerStatRow } from "../../api";
import { useStore } from "../../store";

export default function StatisticsView() {
  const { competitions } = useStore();
  const [competitionId, setCompetitionId] = useState(competitions[0]?.id ?? 1);
  const [category, setCategory] = useState("goals");
  const [rows, setRows] = useState<PlayerStatRow[]>([]);
  useEffect(() => { if (competitions.length && !competitions.some(c => c.id === competitionId)) setCompetitionId(competitions[0].id); }, [competitions, competitionId]);
  useEffect(() => { api.getPlayerStatistics(competitionId, category).then(setRows).catch(() => setRows([])); }, [competitionId, category]);
  return <div className="mx-auto max-w-6xl space-y-4 p-4 lg:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs uppercase tracking-widest text-fm-accent">Historial</div><h2 className="text-2xl font-black">Estadísticas de jugadores</h2></div><div className="flex gap-2"><select value={competitionId} onChange={e=>setCompetitionId(Number(e.target.value))} className="rounded-lg border border-fm-border bg-fm-panel px-3 py-2 text-sm">{competitions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-lg border border-fm-border bg-fm-panel px-3 py-2 text-sm"><option value="goals">Goleadores</option><option value="assists">Asistencias</option><option value="minutes">Minutos</option><option value="rating">Valoración</option><option value="clean_sheets">Porterías imbatidas</option><option value="saves">Paradas</option></select></div></div>
    <div className="overflow-hidden rounded-xl border border-fm-border bg-fm-panel"><table className="w-full text-sm"><thead className="bg-fm-bg text-left text-xs uppercase tracking-widest text-fm-dim"><tr><th className="px-4 py-3">#</th><th className="px-2 py-3">Jugador</th><th className="px-2 py-3">Club</th><th className="px-2 py-3 text-center">PJ</th><th className="px-2 py-3 text-center">Min</th><th className="px-2 py-3 text-center">G</th><th className="px-2 py-3 text-center">A</th><th className="px-2 py-3 text-center">Val</th><th className="px-4 py-3 text-center">Faltas</th><th className="px-2 py-3 text-center">Porterías</th><th className="px-2 py-3 text-center">Paradas</th><th className="px-4 py-3 text-center">Tarjetas</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.player_id}-${r.club_id}`} className="border-t border-fm-border hover:bg-fm-panel2"><td className="px-4 py-3 font-mono text-fm-dim">{i+1}</td><td className="px-2 py-3 font-semibold">{r.player_name}</td><td className="px-2 py-3 text-fm-dim">{r.club_name}</td><td className="px-2 py-3 text-center">{r.appearances}</td><td className="px-2 py-3 text-center">{r.minutes_played}</td><td className="px-2 py-3 text-center font-bold text-fm-accent">{r.goals}</td><td className="px-2 py-3 text-center">{r.assists}</td><td className="px-2 py-3 text-center">{r.average_rating.toFixed(2)}</td><td className="px-4 py-3 text-center">{r.fouls_committed ?? 0}</td><td className="px-2 py-3 text-center">{r.clean_sheets}</td><td className="px-2 py-3 text-center">{r.saves}</td><td className="px-4 py-3 text-center">{r.yellow_cards}/{r.red_cards}</td></tr>)}</tbody></table>{rows.length===0&&<div className="p-8 text-center text-fm-dim">Todavía no hay estadísticas para esta competición.</div>}</div>
  </div>;
}
