import { useEffect, useState } from "react";
import { api, type YouthPlayer, type StaffImpact } from "../../api";
import { EmptyState, MetricCard, Panel, StatusBadge } from "../ui";

export default function YouthView() {
  const [players,setPlayers]=useState<YouthPlayer[]>([]); const [staff,setStaff]=useState<StaffImpact|null>(null); const [msg,setMsg]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=()=>Promise.all([api.getYouth(),api.getStaffImpact()]).then(([p,s])=>{setPlayers(p);setStaff(s);}).catch(e=>setMsg(String(e))).finally(()=>setLoading(false));
  useEffect(()=>{load();},[]);
  const promote=async(id:number)=>{try{setMsg(await api.promoteYouth(id));load();}catch(e){setMsg(String(e));}};
  if(loading)return <div className="mx-auto max-w-6xl p-6"><Panel className="p-8 text-center text-fm-dim">Cargando cantera…</Panel></div>;
  const promotable=players.filter(p=>p.can_promote).length;
  return <div className="mx-auto max-w-6xl space-y-5 p-4 lg:p-6"><div><div className="text-xs font-bold uppercase tracking-[0.2em] text-fm-accent">Desarrollo deportivo</div><h2 className="text-xl font-black">Cantera</h2><p className="text-sm text-fm-dim">Desarrolla talento U12–U20 y promociona a tus mejores juveniles.</p></div><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Juveniles" value={players.length} detail="En la academia" tone="text-fm-sky-300"/><MetricCard label="Promocionables" value={promotable} detail="Listos para subir" tone="text-emerald-300"/><MetricCard label="Preparadores" value={staff?`${staff.youth}/20`:"—"} detail="Calidad aplicada" tone="text-fm-amber-300"/></div>{staff&&<Panel className="p-3 text-sm">Preparadores de cantera: <b className="text-fm-accent">{staff.youth}/20</b> · bonificación de desarrollo aplicada automáticamente al avanzar el día.</Panel>}{msg&&<div className="rounded-lg border border-fm-accent/30 bg-fm-accent/10 px-3 py-2 text-sm">{msg}</div>}{[12,14,16,18,20].map(age=>{const group=players.filter(p=>p.age_group===age);return <Panel key={age} className="overflow-hidden"><div className="border-b border-fm-border bg-fm-bg px-3 py-2 font-bold">U{age} <span className="text-xs font-normal text-fm-dim">· {group.length} jugadores</span></div>{group.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs uppercase tracking-widest text-fm-dim"><tr><th className="px-3 py-2 text-left">Jugador</th><th>Posición</th><th>CA</th><th>PA</th><th>Desarrollo</th><th/></tr></thead><tbody>{group.map(p=><tr key={p.id} className="border-t border-fm-border hover:bg-fm-panel2"><td className="px-3 py-2 font-semibold">{p.flag_path&&<img src={p.flag_path} alt={p.nation} className="mr-2 inline h-3 w-5 rounded object-cover"/>}{p.name}<div className="text-xs text-fm-dim">{p.nation}</div></td><td className="text-center text-xs">{p.position}{p.secondary_position&&` / ${p.secondary_position}`}</td><td className="text-center font-mono">{p.ca}</td><td className="text-center font-mono text-fm-accent">{p.pa}</td><td className="text-center font-mono">+{p.development.toFixed(0)}</td><td className="px-3 text-right">{p.can_promote?<button onClick={()=>promote(p.id)} className="rounded bg-fm-accent px-2 py-1 text-xs font-bold text-black">Promocionar</button>:<StatusBadge>Desde U18</StatusBadge>}</td></tr>)}</tbody></table></div>:<EmptyState title={`Sin jugadores U${age}`} description="Esta categoría todavía no tiene juveniles registrados."/>}</Panel>})}</div>;
}
