import { useState } from "react";
import type { ReactNode } from "react";
import { useStore } from "../store";
import { Icon } from "./ui";

export default function AppShell({ children, unread }: { children: ReactNode; unread: number }) {
  const { screen, setScreen, gameState } = useStore();
  const [open, setOpen] = useState(false);
  if (!gameState) return <>{children}</>;
  const items: { id: typeof screen; label: string; group: string; badge?: number }[] = [
    {id:"dashboard",label:"Dashboard",group:"Club"},{id:"squad",label:"Plantilla",group:"Club"},{id:"tactics",label:"Partido",group:"Club"},{id:"training",label:"Entreno",group:"Club"},{id:"youth",label:"Cantera",group:"Club"},
    {id:"standings",label:"Clasificación",group:"Competición"},{id:"statistics" as typeof screen,label:"Estadísticas",group:"Competición"},{id:"records" as typeof screen,label:"Récords",group:"Competición"},{id:"national-teams" as typeof screen,label:"Selecciones",group:"Internacional"},{id:"fixtures",label:"Calendario",group:"Competición"},{id:"movements" as typeof screen,label:"Ascensos",group:"Competición"},{id:"honours" as typeof screen,label:"Palmarés",group:"Club"},{id:"market",label:"Mercado",group:"Mercado"},{id:"scouting",label:"Ojeo",group:"Mercado"},{id:"finance",label:"Finanzas",group:"Gestión"},{id:"board" as typeof screen,label:"Directiva",group:"Gestión"},{id:"saves",label:"Partidas",group:"Gestión"},{id:"inbox",label:"Buzón",group:"Gestión",badge:unread}
  ];
  return <div className="min-h-screen bg-fm-bg"><header className="sticky top-0 z-20 border-b border-fm-border bg-fm-panel/95 shadow-lg shadow-slate-950/20 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 lg:px-6"><div><div className="text-sm font-black"><span className="text-fm-accent">FM</span>27</div><div className="hidden text-[10px] text-fm-dim md:block">{gameState.game_date} · {gameState.season} · {gameState.user_club_name}</div></div><button aria-expanded={open} aria-controls="main-navigation" aria-label={open ? "Cerrar navegación" : "Abrir navegación"} onClick={()=>setOpen(!open)} className="rounded-lg border border-fm-border px-3 py-2 text-sm md:hidden"><Icon name="menu" /><span className="sr-only">{open?"Cerrar":"Abrir"} menú</span></button><nav id="main-navigation" aria-label="Navegación principal" className={`${open?"flex":"hidden"} absolute left-0 right-0 top-full flex-col gap-1 border-b border-fm-border bg-fm-panel p-3 md:static md:flex md:flex-row md:flex-wrap md:border-0 md:bg-transparent md:p-0`}>{items.map(it=><button key={it.id} aria-current={screen===it.id ? "page" : undefined} onClick={()=>{setScreen(it.id);setOpen(false);}} className={`relative rounded-lg px-2.5 py-1.5 text-left text-xs font-semibold lg:text-sm ${screen===it.id?"bg-fm-accent text-black":"text-fm-dim hover:bg-fm-bg hover:text-white"}`}><span className="mr-1 text-[9px] uppercase opacity-50 md:hidden">{it.group}</span>{it.label}{it.badge?<span className="ml-2 rounded-full bg-rose-500 px-1.5 text-[10px] text-white">{it.badge}</span>:null}</button>)}<button aria-label="Salir de la partida" onClick={()=>setScreen("newgame")} className="rounded-lg border border-fm-border px-2.5 py-1.5 text-left text-xs text-fm-dim">Salir</button></nav></div></header><main>{children}</main></div>;
}
