mod commands;
mod competition;
mod db;
mod editor;
mod engine;
mod finance;
mod season;
mod simulation;
mod training;
mod transfer;
mod world;
mod youth;

use commands::AppState;

pub fn run() {
  tauri::Builder::default()
    .manage(AppState::default())
    .invoke_handler(tauri::generate_handler![
      commands::ping,
      commands::get_app_info,
      commands::test_db,
      commands::seed_world_cmd,
      commands::contract_cmd::get_contracts,
      commands::contract_cmd::renew_contract,
      commands::game::new_game,
      commands::game::get_game_state,
      commands::game::advance_day_cmd,
      commands::game::advance_week_cmd,
      commands::game::get_standings,
      commands::game::get_group_standings,
      commands::game::get_fixtures,
      commands::game::get_squad,
      commands::game::get_competitions,
      commands::game::get_next_fixture,
      commands::game::get_player_statistics,
      commands::national_cmd::get_national_players,
      commands::national_cmd::set_national_callup,
      commands::national_cmd::get_national_manager,
      commands::national_cmd::get_free_national_staff,
      commands::national_cmd::assign_national_manager,
      commands::national_cmd::get_international_fixtures,
      commands::match_live::start_live_match,
      commands::match_live::tick_live,
      commands::match_live::get_live_snapshot,
      commands::match_live::get_last_match_summary,
      commands::match_live::live_tactics,
      commands::match_live::live_substitute,
      commands::match_live::live_timeout,
      commands::match_live::get_pre_match,
      commands::match_live::start_live_match_tactics,
      commands::transfer_cmd::get_loans,
      commands::transfer_cmd::offer_loan,
      commands::transfer_cmd::get_free_agents,
      commands::transfer_cmd::sign_free_agent,
      commands::transfer_cmd::get_market,
      commands::transfer_cmd::get_offers,
      commands::transfer_cmd::make_offer,
      commands::transfer_cmd::respond_offer,
      commands::training_cmd::get_training_schedule,
      commands::training_cmd::get_tactical_automations,
      commands::training_cmd::set_tactical_automation,
      commands::training_cmd::set_training_schedule,
      commands::training_cmd::get_training_progress,
      commands::training_cmd::get_training_types,
      commands::training_cmd::get_staff_impact,
      commands::finance_cmd::get_finance,
      commands::finance_cmd::get_injuries,
      commands::season_cmd::check_season_finished,
      commands::season_cmd::rollover_season_cmd,
      commands::season_cmd::get_season_movements,
      commands::season_cmd::get_honours,
      commands::season_cmd::get_player_history,
      commands::season_cmd::get_competition_records,
      commands::season_cmd::get_club_records,
      commands::scouting_cmd::get_scouting,
      commands::save_cmd::list_save_slots,
      commands::save_cmd::save_game,
      commands::save_cmd::load_game,
      commands::save_cmd::backup_game,
      commands::save_cmd::autosave_game,
      commands::squad_cmd::get_squad_dynamics,
      commands::squad_cmd::get_player_promises,
      commands::squad_cmd::create_player_promise,
      commands::squad_cmd::talk_to_player,
      commands::squad_cmd::get_player_dialogues,
      commands::scouting_cmd::get_scouting_report,
      commands::scouting_cmd::scout_nation,
      commands::youth_cmd::get_youth,
      commands::youth_cmd::promote_youth,
      commands::inbox_cmd::get_inbox,
      commands::inbox_cmd::mark_read,
      commands::inbox_cmd::mark_all_read,
      commands::editor_cmd::editor_init,
      commands::editor_cmd::editor_list_nations,
      commands::editor_cmd::editor_list_clubs,
      commands::editor_cmd::editor_list_players,
      commands::editor_cmd::editor_list_players_by_club,
      commands::editor_cmd::editor_list_contracts,
      commands::editor_cmd::editor_get_finance,
      commands::editor_cmd::editor_update_finance,
      commands::editor_cmd::editor_list_stadiums,
      commands::editor_cmd::editor_create_stadium,
      commands::editor_cmd::editor_update_stadium,
      commands::editor_cmd::editor_delete_stadium,
      commands::editor_cmd::editor_update_contract,
      commands::editor_cmd::editor_assign_player,
      commands::editor_cmd::editor_release_player,
      commands::editor_cmd::editor_list_competitions,
      commands::editor_cmd::editor_list_confederations,
      commands::editor_cmd::editor_list_cities,
      commands::editor_cmd::editor_create_nation,
      commands::editor_cmd::editor_update_nation,
      commands::editor_cmd::editor_delete_nation,
      commands::editor_cmd::editor_create_club,
      commands::editor_cmd::editor_delete_club,
      commands::editor_cmd::editor_update_club,
      commands::editor_cmd::editor_create_player,
      commands::editor_cmd::editor_delete_player,
      commands::editor_cmd::editor_update_player,
      commands::editor_cmd::editor_create_competition,
      commands::editor_cmd::editor_delete_competition,
      commands::editor_cmd::editor_update_competition,
      commands::editor_cmd::editor_get_squad_count,
      commands::editor_cmd::editor_list_staff,
      commands::editor_cmd::editor_list_coaches,
      commands::editor_cmd::editor_create_staff,
      commands::editor_cmd::editor_update_staff,
      commands::editor_cmd::editor_delete_staff,
      commands::editor_cmd::editor_set_coach,
      commands::editor_cmd::editor_set_captain,
      commands::editor_cmd::editor_set_crest,
      commands::editor_cmd::editor_list_confederations_full,
      commands::editor_cmd::editor_update_confederation,
      commands::editor_cmd::editor_set_confed_crest,
      commands::editor_cmd::editor_set_nation_flag,
      commands::editor_cmd::editor_get_player_attributes,
      commands::editor_cmd::editor_update_player_attributes,
      commands::editor_cmd::editor_set_player_photo,
      commands::editor_cmd::editor_set_staff_photo
    ])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
