import { invoke } from "@tauri-apps/api/core";

export type ClubRow = { id: number; name: string; short_name: string; nation: string; reputation: number; primary_color: string; division: string; tier: number | null };
export type CompRow = { id: number; name: string; nation: string; kind: string; competition_type?: string; knockout_rounds?: number; champion_id?: number | null; champion_name?: string | null; group_count?: number; teams_per_group?: number; group_qualifiers?: number; knockout_two_legs?: number };
export type NewGameResult = { game_date: string; season: string; clubs: ClubRow[]; competitions: CompRow[] };
export type GameStateRow = { game_date: string; season: string; user_club_id: number | null; user_club_name: string | null };
export type StandingRow = { group_code?: string | null; position: number; club_id: number; club_name: string; short_name: string; played: number; won: number; drawn: number; lost: number; goals_for: number; goals_against: number; goal_difference: number; points: number };
export type FixtureRow = { id: number; round: number; leg?: number; aggregate_home_score?: number; aggregate_away_score?: number; date: string; home_id: number; home_name: string; home_short: string; away_id: number; away_name: string; away_short: string; home_score: number; away_score: number; status: string; competition_type?: string; cup_winner_id?: number|null; went_to_extra_time?: boolean; went_to_penalties?: boolean; penalty_home_score?: number; penalty_away_score?: number };
export type PlayerRow = { id: number; first_name: string; last_name: string; common_name: string; age: number; nation: string; nation_id?: number; second_nation_id?: number | null; flag_path?: string | null; second_flag_path?: string | null; position: string; secondary_position?: string | null; ca: number; pa: number; wage: number; condition: number; morale: number; happiness: number; squad_role: string; chemistry: number; attrs: { passing:number; finishing:number; dribbling:number; tackling:number; vision:number; anticipation:number; positioning:number; stamina:number; acceleration:number; pace:number; composure:number; technique:number; reflexes:number } };
export type AdvanceResult = { from_date: string; to_date: string; matches_played: number; results: string[] };
export type PlayerStatRow = { player_id:number; player_name:string; club_id:number; club_name:string; appearances:number; minutes_played:number; goals:number; assists:number; shots:number; shots_on_target:number; fouls_committed?:number; yellow_cards:number; red_cards:number; clean_sheets:number; saves:number; average_rating:number };

export type MatchSnapshot = { state: string; half: number; time_seconds: number; score: [number,number]; fouls: [number,number]; shots: [number,number]; yellow_cards: [number,number]; red_cards: [number,number]; powerplay: [boolean,boolean]; timeouts_used: [number,number]; possession: [number,number]; players: { id:number; team_id:number; shirt:number; x:number; y:number; stamina:number; role:string; on_pitch:boolean }[]; ball: [number,number]; ball_holder: number | null; events: { minute:number; second:number; kind:string; team_id:number; player_id:number|null; description:string; x:number; y:number }[] };
export type MarketPlayer = { id:number; name:string; age:number; nation:string; position:string; secondary_position?:string|null; flag_path?:string|null; second_flag_path?:string|null; ca:number; pa:number; club_id:number; club_name:string; club_short:string; value:number; wage:number; contract_end:string; knowledge:number };
export type OfferRow = { id:number; player_id:number; player_name:string; from_club:string; from_club_id:number; to_club:string; to_club_id:number; fee:number; status:string; date:string };
export type LoanRow = { player_id:number; player_name:string; from_club:string; to_club:string; loan_until:string; wage:number };
export type StadiumRow = { id:number; name:string; city:string; city_id:number|null; capacity:number; pitch_type:string; photo_path:string|null; club_id:number|null; club_name:string|null };
export type ContractEditorRow = { id:number; player_id:number; player_name:string; club_id:number; club_name:string; wage_weekly:number; start_date:string; end_date:string; release_clause:number|null; role:string; signing_bonus:number; appearance_bonus:number; clean_sheet_bonus:number; loan_parent_id:number|null; loan_until:string|null; is_active:number };
export type ContractRow = { player_id:number; player_name:string; position:string; flag_path?:string|null; wage:number; end_date:string; release_clause:number|null; role:string; signing_bonus:number; appearance_bonus:number; clean_sheet_bonus:number; renewal_status:string; loan_parent_id:number|null; loan_until:string|null };
export type TacticalAutomation = { id:number; name:string; trigger_type:string; threshold:number; formation:string; tempo:number; pressing:number; defensive_line:number; width:number; enabled:boolean; training_level:number };
export type TrainingRow = { day:number; type_id:number; type_name:string; category:string; intensity:number };
export type StaffImpact = { coach:number; assistant:number; scout:number; youth:number; physio:number; training_bonus:number; scouting_bonus:number; injury_reduction:number };
export type ProgressRow = { player_id:number; name:string; position:string; ca:number; pa:number; age:number; improvement:number };
export type FinanceRow = { club_id:number; club_name:string; balance:number; transfer_budget:number; wage_budget:number; total_wages:number; sponsorship:number; ticket_income:number; prize_money:number; weekly_wages:number; monthly_balance:number };
export type HonourRow = { season:string; competition_id:number; competition:string; club_id:number; club_name:string; honour_type:string };
export type PlayerHistoryRow = { season:string; player_id:number; player_name:string; club_id:number|null; current_ability:number; potential_ability:number; morale:number };
export type NationalPlayerRow = { player_id:number; player_name:string; nation_id:number; nation_name:string; flag_path:string|null; club_name:string|null; position:string; selected:number; callup_status:string };
export type NationalManagerRow = { nation_id:number; staff_id:number; staff_name:string; role:string; tactical:number; motivating:number };
export type InternationalFixtureRow = { id:number; date:string; home_nation_id:number; home_nation:string; home_flag_path:string|null; away_nation_id:number; away_nation:string; away_flag_path:string|null; status:string; home_score:number; away_score:number };
export type RecordRow = { record_type:string; value:number; season:string; player_id:number|null; player_name:string|null; club_id:number|null; club_name:string|null };
export type MovementRow = { season:string; from_competition_id:number; from_competition:string; to_competition_id:number; to_competition:string; club_id:number; club_name:string; movement_type:string; source_position:number };
export type SquadDynamics = { chemistry:number; cohesion:number; captain_id:number|null; vice_captain_id:number|null };
export type PromiseRow = { id:number; player_id:number; promise_type:string; target_value:number; status:string };
export type DialogueRow = { id:number; player_id:number; topic:string; response:string; morale_delta:number; created_at:string };
export type SaveSlot = { id:number; name:string; is_autosave:boolean; updated_at:string };
export type InboxRow = { id:number; sender:string; subject:string; body:string; date:string; is_read:number; is_important:number };
export type ScoutingPlayer = { player_id:number; name:string; club_name:string; nation:string; position:string; secondary_position?:string|null; flag_path?:string|null; second_flag_path?:string|null; knowledge:number; ca_min:number; ca_max:number; pa_min:number; pa_max:number; recommendation:string };
export type ScoutingState = { knowledge_level:number; max_scouts:number; active_assignments:number; players:ScoutingPlayer[]; nations:[number,string][] };
export type ScoutingReport = { player:ScoutingPlayer; strengths:string[]; weaknesses:string[]; attributes:{name:string;value_min:number;value_max:number}[] };
export type YouthPlayer = { id:number; team_id:number; team_name:string; age_group:number; name:string; nation:string; flag_path?:string|null; second_flag_path?:string|null; position:string; secondary_position?:string|null; ca:number; pa:number; development:number; can_promote:boolean };

export type PreMatch = { home_name:string; home_color:string; away_name:string; away_color:string; tactics:{ formation:string; tempo:number; pressing:number; defensive_line:number; width:number; powerplay_enabled:boolean }; squad:{ id:number; name:string; position:string; ca:number }[] };
export type MatchSummary = { match_id:number; date:string; round:number; competition:string; went_to_extra_time?: boolean; went_to_penalties?: boolean; penalty_home_score?: number; penalty_away_score?: number; home:{ id:number; name:string; short_name:string; score:number; shots:number; shots_on_target:number; fouls:number; possession:number }; away:{ id:number; name:string; short_name:string; score:number; shots:number; shots_on_target:number; fouls:number; possession:number }; events:{ minute:number; second:number; kind:string; team_id:number; player_id:number|null; player_name:string|null; description:string }[] };

export const api = {
  newGame: (userClubId?: number) => invoke<NewGameResult>("new_game", { userClubId }),
  getGameState: () => invoke<GameStateRow>("get_game_state"),
  advanceDay: () => invoke<AdvanceResult>("advance_day_cmd"),
  advanceWeek: () => invoke<AdvanceResult[]>("advance_week_cmd"),
  getStandings: (competitionId: number) => invoke<StandingRow[]>("get_standings", { competitionId }),
  getGroupStandings: (competitionId: number) => invoke<StandingRow[]>("get_group_standings", { competitionId }),
  getFixtures: (competitionId: number) => invoke<FixtureRow[]>("get_fixtures", { competitionId }),
  getSquad: (clubId: number) => invoke<PlayerRow[]>("get_squad", { clubId }),
  getCompetitions: () => invoke<CompRow[]>("get_competitions"),
  getNextFixture: (clubId: number) => invoke<FixtureRow | null>("get_next_fixture", { clubId }),
  getPlayerStatistics: (competitionId:number, category?:string) => invoke<PlayerStatRow[]>("get_player_statistics", { competitionId, category }),
  startLive: (matchId: number) => invoke<MatchSnapshot>("start_live_match", { matchId }),
  tickLive: (ticks?: number) => invoke<MatchSnapshot>("tick_live", { ticks }),
  liveTactics: (formation:number, tempo:number, pressing:number, defensiveLine:number, width:number) => invoke<MatchSnapshot>("live_tactics", { formation, tempo, pressing, defensiveLine, width }),
  liveSubstitute: (team:number, outId:number, inId:number) => invoke<MatchSnapshot>("live_substitute", { team, outId, inId }),
  liveTimeout: (team:number) => invoke<MatchSnapshot>("live_timeout", { team }),
  getLive: () => invoke<MatchSnapshot>("get_live_snapshot"),
  getLastMatchSummary: (clubId:number) => invoke<MatchSummary | null>("get_last_match_summary", { clubId }),
  getPreMatch: (matchId: number) => invoke<PreMatch>("get_pre_match", { matchId }),
  startLiveTactics: (payload: { matchId:number; formation:string; tempo:number; pressing:number; defensiveLine:number; width:number; powerplayEnabled:boolean; lineup:number[] }) => invoke<MatchSnapshot>("start_live_match_tactics", { matchId: payload.matchId, formation: payload.formation, tempo: payload.tempo, pressing: payload.pressing, defensiveLine: payload.defensiveLine, width: payload.width, powerplayEnabled: payload.powerplayEnabled, lineup: payload.lineup }),
  getLoans: () => invoke<LoanRow[]>("get_loans"),
  offerLoan: (playerId:number, toClub:number, months:number, wage:number) => invoke<string>("offer_loan", { playerId, toClub, months, wage }),
  getFreeAgents: () => invoke<MarketPlayer[]>("get_free_agents"),
  signFreeAgent: (playerId:number, wage:number, years:number) => invoke<string>("sign_free_agent", { playerId, wage, years }),
  getMarket: () => invoke<MarketPlayer[]>("get_market"),
  getOffers: () => invoke<OfferRow[]>("get_offers"),
  getContracts: (clubId:number) => invoke<ContractRow[]>("get_contracts", { clubId }),
  editorListStadiums: () => invoke<StadiumRow[]>("editor_list_stadiums"),
  editorCreateStadium: (p:{name:string;cityId:number|null;capacity:number;pitchType:string}) => invoke<number>("editor_create_stadium", { name:p.name, cityId:p.cityId, capacity:p.capacity, pitchType:p.pitchType }),
  editorUpdateStadium: (p:{id:number;name:string;cityId:number|null;capacity:number;pitchType:string}) => invoke<void>("editor_update_stadium", { id:p.id, name:p.name, cityId:p.cityId, capacity:p.capacity, pitchType:p.pitchType }),
  editorDeleteStadium: (id:number) => invoke<void>("editor_delete_stadium", { id }),
  editorListContracts: () => invoke<ContractEditorRow[]>("editor_list_contracts"),
  editorSetCaptain: (clubId:number, playerId:number|null, vice=false) => invoke<void>("editor_set_captain", { clubId, playerId, vice }),
  editorUpdateContract: (p: Omit<ContractEditorRow,"player_id"|"player_name"|"club_name">) => invoke<void>("editor_update_contract", p),
  renewContract: (payload: { clubId:number; playerId:number; years:number; wage:number; releaseClause:number|null; role:string; signingBonus:number; appearanceBonus:number; cleanSheetBonus:number }) => invoke<string>("renew_contract", { clubId:payload.clubId, playerId:payload.playerId, years:payload.years, wage:payload.wage, releaseClause:payload.releaseClause, role:payload.role, signingBonus:payload.signingBonus, appearanceBonus:payload.appearanceBonus, cleanSheetBonus:payload.cleanSheetBonus }),
  makeOffer: (playerId:number, fee:number) => invoke<string>("make_offer", { playerId, fee }),
  respondOffer: (offerId:number, accept:boolean) => invoke<string>("respond_offer", { offerId, accept }),
  getTacticalAutomations: () => invoke<TacticalAutomation[]>("get_tactical_automations"),
  setTacticalAutomation: (p:{name:string;triggerType:string;threshold:number;formation:string;tempo:number;pressing:number;defensiveLine:number;width:number;enabled:boolean}) => invoke<string>("set_tactical_automation", { name:p.name, triggerType:p.triggerType, threshold:p.threshold, formation:p.formation, tempo:p.tempo, pressing:p.pressing, defensiveLine:p.defensiveLine, width:p.width, enabled:p.enabled }),
  getTrainingSchedule: () => invoke<TrainingRow[]>("get_training_schedule"),
  setTrainingSchedule: (schedule:[number,number,number][]) => invoke<string>("set_training_schedule", { schedule }),
  getTrainingProgress: () => invoke<ProgressRow[]>("get_training_progress"),
  getStaffImpact: () => invoke<StaffImpact>("get_staff_impact"),
  getTrainingTypes: () => invoke<[number,string,string,number][]>("get_training_types"),
  getFinance: () => invoke<FinanceRow>("get_finance"),
  getInjuries: () => invoke<[number,string,string,string,string][]>("get_injuries"),
  getInbox: () => invoke<InboxRow[]>("get_inbox"),
  getSquadDynamics: () => invoke<SquadDynamics>("get_squad_dynamics"),
  getPlayerPromises: () => invoke<PromiseRow[]>("get_player_promises"),
  createPlayerPromise: (playerId:number, promiseType:string, targetValue:number) => invoke<void>("create_player_promise", { playerId, promiseType, targetValue }),
  talkToPlayer: (playerId:number, topic:string, response:string) => invoke<string>("talk_to_player", { playerId, topic, response }),
  getPlayerDialogues: () => invoke<DialogueRow[]>("get_player_dialogues"),
  listSaveSlots: () => invoke<SaveSlot[]>("list_save_slots"),
  saveGame: (slotId:number, name:string) => invoke<SaveSlot>("save_game", { slotId, name }),
  loadGame: (slotId:number) => invoke<string>("load_game", { slotId }),
  backupGame: (destination:string) => invoke<string>("backup_game", { destination }),
  autosaveGame: () => invoke<SaveSlot>("autosave_game"),
  markRead: (msgId:number) => invoke<void>("mark_read", { msgId }),
  markAllRead: () => invoke<void>("mark_all_read"),
  checkSeasonFinished: () => invoke<boolean>("check_season_finished"),
  rolloverSeason: () => invoke<string>("rollover_season_cmd"),
  getSeasonMovements: (season?: string) => invoke<MovementRow[]>("get_season_movements", { season }),
  getHonours: (clubId?: number) => invoke<HonourRow[]>("get_honours", { clubId }),
  getPlayerHistory: (playerId:number) => invoke<PlayerHistoryRow[]>("get_player_history", { playerId }),
  getNationalPlayers: (nationId:number) => invoke<NationalPlayerRow[]>("get_national_players", { nationId }),
  setNationalCallup: (nationId:number, playerId:number, selected:boolean) => invoke<void>("set_national_callup", { nationId, playerId, selected }),
  getNationalManager: (nationId:number) => invoke<NationalManagerRow|null>("get_national_manager", { nationId }),
  getFreeNationalStaff: (nationId:number) => invoke<[number,string,string,number,number][]>("get_free_national_staff", { nationId }),
  assignNationalManager: (nationId:number, staffId:number) => invoke<void>("assign_national_manager", { nationId, staffId }),
  getInternationalFixtures: (nationId:number) => invoke<InternationalFixtureRow[]>("get_international_fixtures", { nationId }),
  getCompetitionRecords: (competitionId:number) => invoke<RecordRow[]>("get_competition_records", { competitionId }),
  getClubRecords: (clubId:number) => invoke<RecordRow[]>("get_club_records", { clubId }),
  getScouting: () => invoke<ScoutingState>("get_scouting"),
  getScoutingReport: (playerId:number) => invoke<ScoutingReport>("get_scouting_report", { playerId }),
  scoutNation: (nationId:number) => invoke<string>("scout_nation", { nationId }),
  getYouth: () => invoke<YouthPlayer[]>("get_youth"),
  promoteYouth: (youthId:number) => invoke<string>("promote_youth", { youthId }),
  ping: () => invoke<string>("ping"),
};
